# Hostvars variables file
# Placeholder for each variable

wi1:
  private_ip: <value>
wi2:
  private_ip: <value>
wi3:
  private_ip: <value>
manager:
  private_ip: <value>
worker:
  private_ip: <value>
dashboard:
  private_ip: <value>
